### ISSUE TITLE
Remove disabling buttons/checkmarks

### ISSUE THREAD

**Issue by kNelakonda** [cse112-sp24-group2/NoteWorthy#52]
In the previous implementation, some buttons would be disabled when we were either in edit/preview modes. Let's get rid of this now that we are using a rich text editor. 
This should be removing "disable"-related classes, "disable"-related attributes, etc., particularly when the user is editing a note.
This should make some transitions back and forth between the views easier, help with tags, saving, and more.

**Comment by kmags1** [comment]
Fixed in the latest merge
